/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnfitrionRouteImport } from './routes/anfitrion'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PublicarRouteImport } from './routes/publicar'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as ReservasRouteImport } from './routes/reservas'
import { Route as TopRouteImport } from './routes/top'
import { Route as PropiedadesIdRouteImport } from './routes/propiedades.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnfitrionRoute = AnfitrionRouteImport.update({
  id: '/anfitrion',
  path: '/anfitrion',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicarRoute = PublicarRouteImport.update({
  id: '/publicar',
  path: '/publicar',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservasRoute = ReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => rootRouteImport,
} as any)
const TopRoute = TopRouteImport.update({
  id: '/top',
  path: '/top',
  getParentRoute: () => rootRouteImport,
} as any)
const PropiedadesIdRoute = PropiedadesIdRouteImport.update({
  id: '/propiedades/$id',
  path: '/propiedades/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anfitrion': typeof AnfitrionRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/publicar': typeof PublicarRoute
  '/registro': typeof RegistroRoute
  '/reservas': typeof ReservasRoute
  '/top': typeof TopRoute
  '/propiedades/$id': typeof PropiedadesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anfitrion': typeof AnfitrionRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/publicar': typeof PublicarRoute
  '/registro': typeof RegistroRoute
  '/reservas': typeof ReservasRoute
  '/top': typeof TopRoute
  '/propiedades/$id': typeof PropiedadesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anfitrion': typeof AnfitrionRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/publicar': typeof PublicarRoute
  '/registro': typeof RegistroRoute
  '/reservas': typeof ReservasRoute
  '/top': typeof TopRoute
  '/propiedades/$id': typeof PropiedadesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anfitrion'
    | '/favoritos'
    | '/login'
    | '/publicar'
    | '/registro'
    | '/reservas'
    | '/top'
    | '/propiedades/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anfitrion'
    | '/favoritos'
    | '/login'
    | '/publicar'
    | '/registro'
    | '/reservas'
    | '/top'
    | '/propiedades/$id'
  id:
    | '__root__'
    | '/'
    | '/anfitrion'
    | '/favoritos'
    | '/login'
    | '/publicar'
    | '/registro'
    | '/reservas'
    | '/top'
    | '/propiedades/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnfitrionRoute: typeof AnfitrionRoute
  FavoritosRoute: typeof FavoritosRoute
  LoginRoute: typeof LoginRoute
  PublicarRoute: typeof PublicarRoute
  RegistroRoute: typeof RegistroRoute
  ReservasRoute: typeof ReservasRoute
  TopRoute: typeof TopRoute
  PropiedadesIdRoute: typeof PropiedadesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anfitrion': {
      id: '/anfitrion'
      path: '/anfitrion'
      fullPath: '/anfitrion'
      preLoaderRoute: typeof AnfitrionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicar': {
      id: '/publicar'
      path: '/publicar'
      fullPath: '/publicar'
      preLoaderRoute: typeof PublicarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservas': {
      id: '/reservas'
      path: '/reservas'
      fullPath: '/reservas'
      preLoaderRoute: typeof ReservasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top': {
      id: '/top'
      path: '/top'
      fullPath: '/top'
      preLoaderRoute: typeof TopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propiedades/$id': {
      id: '/propiedades/$id'
      path: '/propiedades/$id'
      fullPath: '/propiedades/$id'
      preLoaderRoute: typeof PropiedadesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnfitrionRoute: AnfitrionRoute,
  FavoritosRoute: FavoritosRoute,
  LoginRoute: LoginRoute,
  PublicarRoute: PublicarRoute,
  RegistroRoute: RegistroRoute,
  ReservasRoute: ReservasRoute,
  TopRoute: TopRoute,
  PropiedadesIdRoute: PropiedadesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
